### PR TITLE
Update dEQP shader preprocessor tests from deqp-dev

### PR DESCRIPTION
**Pull request by Oletus**
Pull in latest changes to the tests from deqp-dev branch.

This contains the following changes:

-Double underscores in macro names are now expected to be accepted by the
 compiler. See previous discussion in pull request #1230.
-Unrecognized pragmas are now expected to be accepted by the compiler.
 ESSL 1.00 and 3.00 specs say "If an implementation does not recognize
 the tokens following #pragma, then it will ignore that pragma".
-Non-matching varying invariance is fixed in some #pragma tests.
-Added tests for "defined" operator corner cases for ESSL 3.00 (now
 covered by WebGL 1.0 spec section 6.31)
-Added tests for backslash in a comment for ESSL 3.00

gles2/shaders/preprocessor.test is not a direct copy from dEQP, since
WebGL-specific changes apply to the behavior of extension directives.

dEQP scripts are updated with support for "build_successful" expectation.
Also, testFailed() is now called if the shader file can't be parsed to
get debugging information automatically.

### CODE REVIEW

**Comment by kenrussell** [comment]
Thanks Olli for this contribution. It looks good overall. @RafaelCintron @grorg @jdashg @toji in particular do you have any comments?

I'd like to ask @zhenyao to review this too. Mo, could you please also merge this once other feedback has been assembled? Thanks.

**Comment by kenrussell** [comment]
Also CC'ing @jasomobica in case he has any feedback.

**Comment by Oletus** [comment]
I found one issue in the shaders: they test that "#pragma ¤¤½" compiles - based on that unrecongized pragmas should be ignored. This goes against WebGL mandating an error when there are invalid characters in the shader. Pyry suggested to me that I should open a Khronos bug about this for discussion, so I did that: https://cvs.khronos.org/bugzilla/show_bug.cgi?id=14939 (private link).

**Comment by kenrussell** [comment]
Thanks for finding that behavioral difference Olli. Perhaps we could merge in the majority of these tests, leaving just that one for future work. Or we could discuss this at the F2F.

**Comment by kenrussell** [comment]
One other comment: WebGL implementations already strip out Unicode characters from comments before even passing the shaders to ANGLE's shader translator, to make it easier for users to add comments in their native language. It would be straightforward to change the WebGL spec to allow these sorts of pragmas as long as they can be safely stripped out of shaders.

**Comment by zhenyao** [comment]
@Oletus Can you get rid of the "#pragma ¤¤½" case and merge the rest?

@kenrussell I prefer failing shaderSource(), so we don't have to perform any complicated processing in WebGLRenderingContext at that stage except for stripping out comments.

**Comment by Oletus** [comment]
Removed the invalid characters from the tests. I put that in a separate commit, that way it will be easier to track which tests were intentionally changed compared to native dEQP. I noticed that the problem wasn't unique to the pragma tests either, but some extension directive tests had the same issue.

**Comment by kenrussell** [comment]
LGTM. Let's let @zhenyao re-review and merge this. He's out until next Monday.

**Comment by zhenyao** [comment]
LGTM

**Pull request merged**
