### PR TITLE
fixes for gl-object-get-calls.js

### PR DESCRIPTION
**Pull request by howareyou322**

### CODE REVIEW

**Comment by zhenyao** [comment]
GL_COLOR is not a valid arg when default framebuffer is bound.  GL_BACK is correct.

**Comment by jdashg** [comment]
Right, COLOR is only used for ClearBuffer and InvalidateFramebuffer.

**Comment by howareyou322** [comment]
Thanks for comment, I also found it from spec. Will create another pull request to enable stencil.

**Comment by kenrussell** [comment]
Thanks. If you submit another pull request, please consider the bug I filed about it https://github.com/KhronosGroup/WebGL/issues/1426 . Ideally it should test both with and without a default stencil buffer, rather than only one of those cases.

**Comment by howareyou322** [comment]
I'm looking into #1426 now.

**Pull request closed without merging**
