### PR TITLE
Add a regression test for crbug.com/804118

### PR DESCRIPTION
**Pull request by zhenyao**

### CODE REVIEW

**Comment by zhenyao** [comment]
@kainino0x @kenrussell @jdarpinian Please review.

**Comment by kenrussell** [comment]
Looks good Mo, but can you fix the line endings so the Travis build isn't broken for this new test? I'm not sure whether there's a Windows CR/LF issue, or something else. Tell me tomorrow if you need help.

**Comment by kenrussell** [comment]
Merged manually, fixing whitespace errors, in https://github.com/KhronosGroup/WebGL/commit/efdb969820ea7e2bd73f6a00da5f983a7357cc09 . Closing.

**Comment by kenrussell** [comment]
Oops, sorry, I just realized that I pushed that to the wrong repository. This is the top-of-tree commit in KhronosGroup/WebGL containing the merge:
https://github.com/KhronosGroup/WebGL/commit/5c6e631e4a8a6306d74e49d4c6c51425f5a33a21

**Comment by zhenyao** [comment]
This slipped out of my radar. Thanks for fixing the style issue and merging it!

**Pull request closed without merging**
