### PR TITLE
Reject PVRTC extension in favor of ASTC, ETC, and S3TC.

### PR DESCRIPTION
**Pull request by kdashg**

### CODE REVIEW

**Comment by jdashg** [comment]
We recently passed on creating an extension for PVRTC+sRGB in #2473, so rejecting PVRTC as a whole might make sense.

**Comment by MarkCallow** [comment]
I'm not sure any iOS devices support S3TC so we need to be cautious about suggesting that as an alternative. My not too ancient iPad Pro does not. I suppose expiration of the S3 patent might have changed things though.

**Comment by jdashg** [comment]
Generally iOS devices should have at least ETC, though sufficiently old devices might not have even that, I suppose.

**Comment by jdashg** [comment]
It looks like iOS Webkit has not yet implemented either ETC extension:
https://webglstats.com/webgl/extension/WEBGL_compressed_texture_etc?platforms=000000840000000000

**Comment by lexaknyazev** [comment]
Compressed texture support on a hardware side:
- pre-A7 (before iPhone 5S): PVRTC only
- A7: PVRTC & ETC 1/2
- A8 and newer: PVRTC, ETC 1/2, ASTC

For some reasons, iOS WebKit exposes only PVRTC extension.

**Comment by kenrussell** [comment]
Until we hear approval from Apple and until they implement WebGL's ETC compressed texture extension, this should be left as community approved to avoid invalidating their implementation.

**Comment by jdashg** [comment]
Since the jury's still out, this should stay open until we have more information.

**Comment by kenrussell** [comment]
After discussion with folks on Slack (@kkinnunen-apple and @lexaknyazev ), the preference was to call out this extension as deprecated, rather than rejecting it. This was done in #3398 .

**Pull request closed without merging**
