### PR TITLE
Generic vertex attrib values are vertex shader state.

### PR DESCRIPTION
**Pull request by jdashg**

### CODE REVIEW

**Comment by zhenyao** [comment]
I disagree.  If generic attrib values are per vertex shader, then VertexAttrib{I}* function should generate INVALID_OPERATION of no program is bound, but we don't have that error specified.

**Comment by jdashg** [comment]
GLES 2.0.25 p150:
https://www.khronos.org/registry/gles/specs/2.0/es_full_spec_2.0.25.pdf

GL2.0 p291:
https://www.opengl.org/registry/doc/glspec20.20041022.pdf

I agree, they should generate INVALID_OP. I have patches to add this to Firefox.

**Comment by jdashg** [comment]
Oh, yeah, I guess they might be saying "this is state for vertex shaders", but not actually "this is state attached to vertex shaders?". That does seem more likely.

**Comment by jdashg** [comment]
Yeah, that must be it. If only I could PR the GL specs!

**Pull request closed without merging**
