### PR TITLE
Add tests for uploading sub-rectangles of HTMLImageElements.

### PR DESCRIPTION
**Pull request by kenrussell**
Verified against Chromium's implementation in https://codereview.chromium.org/2458943002 .

### CODE REVIEW

**Comment by kenrussell** [comment]
@zhenyao @jdashg in particular, please review.

**Comment by zhenyao** [comment]
LGTM
If no further comments from Jeff, feel free to merge yourself.

**Comment by kenrussell** [comment]
@jdashg any comments? This has been tested with this Chromium CL: https://codereview.chromium.org/2458943002/ .

**Comment by kenrussell** [comment]
Landing this now; we need these tests in place to continue with the others.

**Pull request merged**
