### PR TITLE
Added partial transform feedback API test. Focuses on binding.

### PR DESCRIPTION
**Pull request by toji**

### CODE REVIEW

**Comment by toji** [comment]
Updated commit based on @jdashg's comments (which disappeared in a puff of smoke when I uploaded the amended commit...)

**Comment by kenrussell** [comment]
Thanks, this looks good. It would be helpful if you could look at sdk/tests/deqp/functional/gles3/transformfeedback.html and see whether there's any overlap between these tests.

**Comment by kenrussell** [comment]
I'll leave this to @jdashg to merge since it sounds like he was already reviewing it.

**Comment by jdashg** [comment]
Cool, thanks.

**Pull request merged**
