### PR TITLE
Use three colors in tex-image tests

### PR DESCRIPTION
**Pull request by fritzk**
Using three colors makes it apparent if
the selected rectangle is upside down.

### CODE REVIEW

**Comment by jdashg** [comment]
Red and green are already stacked vertically. Can you be more precise about why you want this?

**Comment by fritzk** [comment]
I would like to make sure that the selected rectangle is oriented correctly.  Currently there is nothing to say that the red or green rectangle is right side up or upside down after using texImage2D.  By adding a third color it the selected rectangle is now either red/blue or blue/green and the orientation can be derived.

**Comment by fritzk** [comment]
Isn't that what tex-image-and-sub-image-2d-with-canvas-sub-rectangle.js is doing now?  Using UNPACK_SKIP_PIXELS and UNPACK_SKIP_ROWS?

I was working on this today already.  If you still want it back in tex-image-and-sub-image-2d-with-webgl-canvas.js I can start work on figuring out how to add a optional sub-rectangle to the test case.

**Comment by kenrussell** [comment]
Looking again at tex-image-and-sub-image-2d-with-canvas-sub-rectangle.js, I see that it's in fact testing both 2D canvas and WebGL sources. Was concerned that it might be missing some cases.

If you're convinced that the existing tests catch all possible errors in the implementation then it's ok to not make any changes to the tests.

**Comment by kenrussell** [comment]
@fritzk could you please confirm whether this CL is really needed, or whether tex-image-and-sub-image-2d-with-canvas-sub-rectangle already covered these cases (and caught the associated regressions)? Thanks.

**Comment by kenrussell** [comment]
@fritzk confirmed offline that this change isn't strictly needed - the scenario is covered by the other tests - so I'm closing this. Sorry for creating unnecessary work for you Fritz.

**Pull request closed without merging**
