### PR TITLE
Update WebGL spec to align internalformat type of TexImage{2D|3D} with ES spec

### PR DESCRIPTION
**Pull request by qkmiao**
Change type of internalformat from GLenum to GLint.

### CODE REVIEW

**Comment by kenrussell** [comment]
Thanks, looks good but please re-run extract-idl.py in specs/latest/1.0 and specs/latest/2.0 as well and include the .idl file changes.

**Comment by qkmiao** [comment]
@kenrussell updated the pr according your comments. Thanks!

**Comment by kenrussell** [comment]
Thanks. Not sure whether the 2.0/*.idl changes were missed but I'll merge this and double-check.

**Comment by kenrussell** [comment]
For the record, the 2.0/webgl2.idl file wasn't changed by these spec changes.

**Pull request merged**
