### PR TITLE
Add a test case in for loop condition

### PR DESCRIPTION
**Pull request by qjia7**
The test in for loop expression can't expose an Intel driver bug. We
add another test in for loop condition to conver it.

### CODE REVIEW

**Comment by qjia7** [comment]
PTAL Thanks.

**Comment by zhenyao** [comment]
What's wrong with the original code? It looks OK to me.

**Comment by qjia7** [comment]
The problem is that the original code can't expose the Intel driver bug. The corresponding test is 'Pass' when u is false. However, if we use 'u && foo()' as the for condition like other 'while' shaders, the same error can be reproduced. Since this file is mainly to test the loop condition, I think it's better to put 'u && foo()'  as a condition. Obviously, Intel driver has bug when processing 'u && foo()' as for and while loop condition. I will report this bug to our driver team. Thanks.

**Comment by zhenyao** [comment]
The description for this test case is "in for loop expression", which is accurate.

I think the original test is still valuable.

Can you just add another test case with description "in for loop condition"?

**Comment by qjia7** [comment]
>Can you just add another test case with description "in for loop condition"?

Done. Thanks for your suggestion.

**Comment by zhenyao** [comment]
LGTM
Thanks

**Pull request merged**
