### PR TITLE
Document that WEBGL_lose_context extension should destroy graphics

### PR DESCRIPTION
**Pull request by kenrussell**
resources.

### CODE REVIEW

**Comment by kenrussell** [comment]
Split this off from #2283 based on feedback from @jdashg .

@zhenyao @kainino0x @grorg @RafaelCintron @Oletus, in particular, please review. Thanks.

**Comment by kainino0x** [comment]
LGTM

**Comment by RafaelCintron** [comment]
LGTM

**Comment by kenrussell** [comment]
Thanks for your feedback. Merging now.

**Pull request merged**
