### PR TITLE
Add negative tests for invariance in ESSL 3.00 shaders.

### PR DESCRIPTION
**Pull request by kenrussell**
Follow-up to #1924 .

### CODE REVIEW

**Comment by kenrussell** [comment]
@zhenyao PTAL.

@jdashg @qkmiao @jchen10 @null77 @Kangz @vonture FYI. I don't anticipate these will cause any problems. They already pass in Chrome and I'm quite sure ANGLE's shader translator is catching the errors, so they should pass in Firefox too.

**Comment by kenrussell** [comment]
Hold off merging this for a second -- forgot the title.

**Comment by kenrussell** [comment]
Ready for review.

**Comment by zhenyao** [comment]
LGTM

**Pull request merged**
