### PR TITLE
Throw exception if pixels data is null for CompressedTex{Sub}Image

### PR DESCRIPTION
**Pull request by qkmiao**
https://codereview.chromium.org/1527723003/ fixes this test.

### CODE REVIEW

**Comment by toji** [comment]
Thanks for the test. This looks good but I'm going to make one minor request: shouldThrowException seems like a useful utility function that multiple tests may want to use. Could you put it in webgl_test_utils.js instead?

**Comment by kenrussell** [comment]
Actually, there's already a "shouldThrow" in sdk/tests/js/js-test-pre.js . Let's re-use that.

**Comment by qkmiao** [comment]
Thanks! The existed shouldThrow is used now.

**Comment by toji** [comment]
Thanks for the update! Merging.

**Pull request merged**
