### PR TITLE
Add conformance2/uniforms/uniform-block-idents-as-expr.

### LINKED ISSUE #3644: Clarify discarded expressions of  uniform block reference through instance name only
Consider uniform block declaration with a _instance-name_:

`uniform MyBlock { int x; int y; } b; `

The spec spends effort to disallow using `b`  without any field access. You aren't allowed to use `MyBlock`, so it is not easy to refer to plain `b` in a valid program.

Except, you can use it in a discarded statement expression, like `b;`  or in a comma expression like `somethingsomething, b;`

This is a problem because some rewrite steps don't anticipate uniform blocks, and ANGLE assert with these.

Would it be in the spirit of the spec to fail these programs, or should they pass?

As per my reading, that could affect the statically used uniform counts? However, I can't parse the spec to understand if individual members of an uniform block are affected with different static use counts. E.g. if I refer to b.x; does it mean that b.y can be optimized away if not used? Would b; in this case mean that all uniform variables of that block are statically used.

https://registry.khronos.org/OpenGL/specs/es/3.0/GLSL_ES_Specification_3.00.pdf
>For uniform blocks, the application uses the block name to identify the block. Block names have no other use within a shader beyond interface matching; it is an error to use a block name at global scope for anything other than as a block name (e.g., use of a block name for a global variable name or function name is currently reserved). It is a compile-time error to use the same block name for more than one block declaration in the same shader interface (as defined above) within one shader, even if the block contents are identical.

### PR DESCRIPTION
**Pull request by kdashg**
Fixes #3644.

Fails 4-6 subtests on top-of-tree Chrome and Firefox.

### CODE REVIEW

**Comment by kdashg** [comment]
(I only tested on Windows)

**Comment by kenrussell** [comment]
Thanks very much Kelsey for putting this together. On current Chromium, the failing cases are:

```
test[13]: {"programOk":false,"vsrc":"uniform BlockName { vec4 member; } InstanceName;\nvoid f() { InstanceName; }","fsrc":""}
FAIL Expected linked: false, was true

test[14]: {"programOk":false,"vsrc":"","fsrc":"uniform BlockName { vec4 member; } InstanceName;\nvoid f() { InstanceName; }"}
FAIL Expected linked: false, was true

test[23]: {"programOk":false,"vsrc":"uniform BlockName { vec4 member; } InstanceName[1];\nvoid f() { InstanceName; }","fsrc":""}
FAIL Expected linked: false, was true

test[24]: {"programOk":false,"vsrc":"","fsrc":"uniform BlockName { vec4 member; } InstanceName[1];\nvoid f() { InstanceName; }"}
FAIL Expected linked: false, was true

test[27]: {"programOk":false,"vsrc":"uniform BlockName { vec4 member; } InstanceName[1];\nvoid f() { InstanceName[0]; }","fsrc":""}
FAIL Expected linked: false, was true

test[28]: {"programOk":false,"vsrc":"","fsrc":"uniform BlockName { vec4 member; } InstanceName[1];\nvoid f() { InstanceName[0]; }"}
FAIL Expected linked: false, was true
```

What would be needed to pass these? Does ANGLE's shader translator need to fail compilation of these vertex / fragment shaders? Is more complex validation needed at link time?

**Review by kenrussell — APPROVED** [review]

**Review by kkinnunen-apple — APPROVED** [review]
Thank you.

**Review by lexaknyazev — APPROVED** [review]

**Comment by kenrussell** [comment]
Thanks Kelsey for the test.

**Pull request merged**
