### PR TITLE
Promote KHR_parallel_shader_compile to community approved.

### PR DESCRIPTION
**Pull request by kenrussell**
This extension significantly improves startup time and smoothness of
WebGL applications loading many shader programs.

### CODE REVIEW

**Comment by kenrussell** [comment]
@jdashg @RafaelCintron @grorg please review - as discussed at the last WebGL working group meeting, and as emailed to public_webgl.

**Comment by jdashg** [comment]
(copied from the email thread)

         
           
      
I expect this to be best-practice with or without this extension enabled:
```
for (const x of shaders)
   gl.compileShader(x);
for (const x of programs)
   gl.linkProgram(x);
```
With the extension, apps would be able to poll whether programs have
linked without janking, but these are likely to take the same total
wall time to link:
```
function* linkingProgress(programs) {
   const ext = gl.getExtension('KHR_parallel_shader_compile');
   let todo = programs.slice();
   while (todo.length) {
      if (ext) {
         todo = todo.filter(x => !gl.getProgramParameter(x, ext.COMPLETION_STATUS_KHR));
      } else {
         const x = todo.pop();
         gl.getProgramParameter(x, gl.LINK_STATUS);
      }
      yield 1.0 - (todo.length / programs.length);
   }
}
```

**Comment by kenrussell** [comment]
Since no objections and since some users have confirmed on public_webgl that with the latest fixes to Chrome, querying the completion status of shaders is fast and avoids blocking, this should be easily implementable on all browsers by updating ANGLE. Merging now.

**Comment by jdashg** [comment]
Just to be clear: Firefox does not integrate with ANGLE in such a way that this is trivially implementable for non-windows platforms.

**Comment by kenrussell** [comment]
Chrome also has more work to do in order to expose this extension on non-Windows platforms. However, the Windows platform is the one with the longest compilation times.

**Pull request merged**
