### PR TITLE
Add non-normative note per #1167 about packing algorithm's guarantees.

### PR DESCRIPTION
**Pull request by kenrussell**

### CODE REVIEW

**Comment by kenrussell** [comment]
@jdashg @grorg Please review.

@toji @zhenyao FYI.

**Comment by zhenyao** [comment]
LGTM

**Comment by toji** [comment]
LGTM as well. Thank goodness for layout(std430). :P

**Comment by kenrussell** [comment]
Will still wait another 24 hours for @jdashg or @grorg to review.

Note: Brandon's referring to the std140 layout for uniform blocks that is coming in WebGL 2.0, and which will help a lot with these sort of issues.

**Comment by kenrussell** [comment]
Since there haven't been any further comments, merging now.

**Pull request merged**
