### PR TITLE
Fix WebGL1 conformance tests to the API changes (null-able).

### PR DESCRIPTION
**Pull request by zhenyao**
Note this is ToT. Once this lands, I'll fix the earlier snapshots.

### CODE REVIEW

**Comment by zhenyao** [comment]
@kenrussell @jdashg @kainino0x

**Comment by zhenyao** [comment]
Oops. Thanks for catching this bug.

**Comment by kenrussell** [comment]
These fixes look great -- are they complete at this point?

**Comment by zhenyao** [comment]
For WebGL1, yes, it's complete.

**Comment by kenrussell** [comment]
Excellent. Thank you for diligently taking care of these. Merging now.

**Comment by slacka** [comment]
@zhenyao 
Can your changes be backported? I'm seeing the following failures on [1.0.3.](https://www.khronos.org/registry/webgl/conformance-suites/1.0.3/webgl-conformance-tests.html
)

> conformance/buffers/buffer-data-array-buffer.html
> conformance/context/context-lost.html
> conformance/misc/bad-arguments-test.html
> conformance/misc/error-reporting.html
> conformance/misc/null-object-behaviour.html
> conformance/programs/get-active-test.html
> conformance/state/gl-object-get-calls.html

With Chrome Canary. On 1.0.4 those tests are passing.

**Comment by zhenyao** [comment]
I thought I did, but apparently not. I am on it.

**Pull request merged**
