### PR TITLE
attribute USVString WebGLObject.label, application-provided.

### PR DESCRIPTION
**Pull request by kdashg**
This is similar to WebGPU's `GPUObjectBase.label`.

### CODE REVIEW

**Comment by kdashg** [comment]
https://www.w3.org/TR/webgpu/#gpuobjectbase
```js
interface mixin GPUObjectBase {
    attribute USVString label;
};
```

**Comment by greggman** [comment]
The difference between WebGPU's label and WebGL is that, AFAIK, WebGPU always returns an object. WebGL does not

```
// on lost context
const b = gl.createBuffer();
b.label = "verts";              // crash!, can't set property label of `null`
```

WebGPU doesn't have this issue

**Comment by kdashg** [comment]
I strongly prefer the ergonomics of .label, and would rather champion infallible allocations instead of reduced ergonomics.

**Comment by greggman** [comment]
In the spirit of the fact that WebGL is supposed to make porting OpenGLES code easier, isn't  [`WEBGL_debug`](https://registry.khronos.org/webgl/extensions/proposals/WEBGL_debug/) the more WebGL-ish thing to support?

Of course it's doesn't have to be either/or but still.

**Comment by kdashg** [comment]
I believe my proposal is the best way forward for the most users.

**Review by kkinnunen-apple — APPROVED** [review]
Looks good, thanks.

**Review by kenrussell — APPROVED** [review]
This direction sounds good. While it's a different API style than other WebGL extensions, it's expected that this would be implementable/supportable at the native level pretty much ubiquitously.

**Pull request merged**
