### PR TITLE
Fix bugs in blitFramebuffer-filter-outofbounds.html

### PR DESCRIPTION
**Pull request by Richard-Yunchao**
Sorry, stay too late yesterday... 

PTAL. Thanks! @zhenyao , @kenrussell .

### CODE REVIEW

**Comment by zhenyao** [comment]
lgtm

**Comment by Richard-Yunchao** [comment]
I am not 100% sure whether I understand this issue correctly: 
For pixels lying outside the read fb, the corresponding dst pixels should keep untouched. But the outside pixels should be considered for scaling when blitting. 
For pixels lying outside the draw fb, the pxiels are simply ignored (dst region intersects with draw buffers), the outside pixels would not be considered for scaling when blitting.

**Comment by Richard-Yunchao** [comment]
@zhenyao and @kenrussell .

**Comment by zhenyao** [comment]
What I am saying is (this is the wrong place because the discussion was at another pull request), for a pixel on the boundary of draw fb, if the filter is LINEAR, then its value could be determined by more than one pixel from the read fb, and these pixels could be partially in bound, partially out of bound.

**Pull request merged**
