### PR TITLE
Enable Lint tool on Travis CI

### PR DESCRIPTION
**Pull request by Honry**

### CODE REVIEW

**Comment by Honry** [comment]
Here's a [short guide]( https://github.com/crosswalk-project/crosswalk-test-suite/issues/1680#issuecomment-158261425) for setup Travis CI on your test repo, just for your reference. The ones you have administrative access to are the ones you can enable the service hook for.

**Comment by Honry** [comment]
@renchenglei, @kenrussell, @zhenyao, PTAL. Thanks.

**Comment by kenrussell** [comment]
Thanks @Honry . It turns out I don't have permission to enable Travis on this repository. I'll ask the webmaster about it.

**Comment by kenrussell** [comment]
OK, looks like the permissions just took some time to propagate. Thanks again for this contribution; let's merge and see if it works.

**Pull request merged**
