### PR TITLE
Test the bias parameter to the texture GLSL function

### PR DESCRIPTION
**Pull request by greggman**
In GLSL there's a function `texture(sampler, texcoords, bias)`.
This test tests that `bias` works and that it is limited to
its advertised limits from `MAX_LOD_BIAS`

I believe ANGLE fails this test on several platforms as it returns a `MAX_LOD_BIAS` of `2.0` but actually allows the bias to go past the limit

### CODE REVIEW

**Comment by greggman** [comment]
I thought I'd mention this test seems to fail on Firefox for a different reason. See

https://bugzilla.mozilla.org/show_bug.cgi?id=1772197

**Comment by cndv3996** [comment]
For a long time havn't worked on conformance tests. Brought back some miserable memories!

I'm trying to understand your algorithms.
Say you draw the LOD level (say 15) to respective mipmaps.

As we go through pixels. This line:
`vec4 texColor = texture(tex, v_uv, (gl_FragCoord.x - 0.5) * biasMult);  // the color we care about`

Will use LOD bias from say 0 to 14?
And 2.0 should be the function really takes in.

And we'll never expect the pixel we read out exceed 3?
Which means we only should read from mipmap #0 to #2? Never lower resolution?

**Comment by greggman** [comment]
> For a long time havn't worked on conformance tests. Brought back some miserable memories!
> 
> I'm trying to understand your algorithms. Say you draw the LOD level (say 15) to respective mipmaps.
> 
> As we go through pixels. This line: `vec4 texColor = texture(tex, v_uv, (gl_FragCoord.x - 0.5) * biasMult); // the color we care about`
> 

As it says in the comments

```
// Draw each mip. Result should be [mip0, mip1, mip2, ...]
```

And

```
// Draw each mip. Result should be [mipMax, mipMax - 1, mipMax - 2, ...]
```

> Will use LOD bias from say 0 to 14? 

yes

> And 2.0 should be the function really takes in.

I don't understand this comment. 

> And we'll never expect the pixel we read out exceed 3? Which means we only should read frommipmap #0 to #2? Never lower resolution?

We should not be able to read past +/- whatever `gl.getParameter(gl.MAX_TEXTURE_LOD_BIAS)` returns for a given computed mip following the lod formula from the spec. In other words, based on the texture coordinates mip level will be chosen. The bias is added after that calculation. The code setups the UV coords first so that calculation will choose the largest mip level

```
// set the UVs so we'd get mip level 0 for every pixel
```

Then it adds biases 0 to maxLod

Then

```
// set the UVs so we'd get highest mip level (the 1x1 level mip) for every pixel
```

then it subtracts biases 0 to maxLod

**Comment by cndv3996** [comment]
Thanks, I think I get it.

Draw 2 times:
1. At mip level 0,
As we draw a pixel to color buffer,  we read first from mip levels (starting from 0) of texture ascendingly.
We'll give biases from 0 to maxLod and even larger as you mentioned.

But texture() should acctually read from 0 to maxLod and not larger levels.

2. Vice Versa.

Great to learn it, thanks!

**Review by kenrussell — COMMENTED** [review]
Sorry for the long delay reviewing. This test passes in both Chromium and Safari; they're using different backends (OpenGL vs. Metal), so it looks like the failures seen in Firefox Nightly are in the browser and not the test.

**Review by kenrussell — APPROVED** [review]

**Comment by kenrussell** [comment]
Note: tested on M1 MacBook Pro.

**Comment by kenrussell** [comment]
Correction: per Kelsey's feedback on https://bugzilla.mozilla.org/show_bug.cgi?id=1772197 , there was a bug in the computation of maxLODs. Fixing that makes the test pass on all browsers.

**Review by kenrussell — APPROVED** [review]
The test's now passing on all browsers on the M1. Merging.

**Pull request merged**
