### PR TITLE
Increase tolerance to 8 from 3.

### PR DESCRIPTION
**Pull request by kenrussell**
Found necessary on multiple platforms in http://crbug.com/1165751 .

Follow-up to #3214 .

### CODE REVIEW

**Comment by kenrussell** [comment]
@jdashg or @shrekshao : please review. Thanks.

**Comment by kenrussell** [comment]
Or @kainino0x ? Thanks.

**Review by shrekshao — APPROVED** [review]

**Comment by kenrussell** [comment]
Thanks @shrekshao for your review. I don't think this is controversial - merging now.

**Comment by kenrussell** [comment]
BTW, slight differences in the rendered output between these two different mathematical expressions - which use constants / variables differently - have appeared on multiple platforms and GPUs.

**Review by jdashg — COMMENTED** [review]
This is probably fine though I would have preferred a working hypothesis for why.

**Comment by kenrussell** [comment]
I'm pretty sure it's due to differing optimizations being done by the driver's shader compiler in the two code paths.

**Pull request merged**
