### PR TITLE
Add a test for tricky loop conditions

### PR DESCRIPTION
**Pull request by Oletus**
Some types of transformations in shader translation may need to add
new statements to implement certain types of expressions. In case an
expression inside a loop condition or loop expression requires this
kind of a transformation, it needs special handling. Add a test for
bugs in this area.

There are known failures in this test on ANGLE's DirectX backend and
NVIDIA's OpenGL drivers.

### CODE REVIEW

**Comment by zhenyao** [comment]
Thanks for the test cases. LGTM

**Comment by Kangz** [comment]
Stop adding tests that fail on NVIDIA Linux or we'll never get to 100 % passing! :P

**Comment by zhenyao** [comment]
We should welcome tests that exposes driver bugs or implementation bugs.  Don't worry, all such driver bugs that are non-critical will be put under --min-version=2.0.1.

**Comment by kenrussell** [comment]
@Kangz was joking. :) These are great test cases Olli and they'll help ensure consistency of WebGL 2.0 / ES 3.0. Please keep them coming. LGTM after the fact.

**Pull request merged**
