### PR TITLE
Add imageSize to compressedTex{Sub}Image{2|3}D.

### PR DESCRIPTION
**Pull request by zhenyao**
This is to address https://github.com/KhronosGroup/WebGL/issues/2233, the spec part.

@kenrussell @kainino0x @jdashg PTAL

### CODE REVIEW

**Comment by kenrussell** [comment]
Thanks for putting this together Mo.

Should we update the detailed documentation for these entry points to discuss the imageSize argument?

@jdashg please review this -- it's an oversight in the specification for these APIs. Arguably the imageSize argument is redundant -- for all of the existing compressed texture formats, it can be computed from the internal format, width and height -- but we specify it for the ArrayBufferView variants of these methods, so to avoid deviation from the ES3 spec, it should be added here.

**Comment by zhenyao** [comment]
imageSize related documentation is exactly the same as the man pages, usually we avoid repeating it if there isn't any WebGL specific rules.

**Comment by jdashg** [comment]
I think it makes the most sense to also insert imageSize args before the ArrayBufferView args, and remove the optional length arg.
This would most match the GLES spec, and be most consistent between entrypoints.

Also I don't think I can take this change in Firefox 51, but we can errata it for 51 and fix in 52.

LGTM otherwise.

**Comment by zhenyao** [comment]
Same here with Chrome. We have to wait for the next release to update this.

Let me merge this to move forward.

As for the imageSize with ArrayBufferView, in theory I agree it's a good idea, but since both Firefox and Chrome will launch WebGL2 with a different signature, I have two concerns: 1) we might break contents if they are out already 2) make conformance tests pass for both versions will be challenging.

We can discuss further in the working group meeting today.

**Pull request merged**
