### PR TITLE
Deinit vertex attrib array state in InstancedRenderingCase

### PR DESCRIPTION
**Pull request by xhcao**
Please help to review it, thank you.

### CODE REVIEW

**Comment by Kangz** [comment]
LGTM too

**Comment by zhenyao** [comment]
The fix looks good in itself.  I am curious, why this isn't an issue on some platforms but only on others?

**Comment by xhcao** [comment]
@zhenyao 
In mesa+i965 platform:
case 1):     gl.getAttribLocation(program, 'a_position') return 12;
                 gl.getAttribLocation(program, 'a_instanceR')  return 0;
case 2):     gl.getAttribLocation(program, 'a_position') return 0;
But in nvidia platform, It seems that gl.getAttribLocation(program, 'a_position') are all return 0 in case 1) and case 2), so there is no overriding situation.
It seems that the distribution location values algorithm of mesa is different as nvidia.

**Comment by zhenyao** [comment]
Thanks for the explanation.

**Pull request merged**
