### PR TITLE
Fixed Khronos bug 14551: WebGL 1.0.3: ternary-operators-in-global-ini…

### PR DESCRIPTION
**Pull request by kenrussell**
…tializers

Added "const" to the declarations of the variables on the two sides of the ternary operator.

### CODE REVIEW

**Comment by kenrussell** [comment]
@zhenyao @RafaelCintron please review.

**Comment by zhenyao** [comment]
LGTM

**Comment by RafaelCintron** [comment]
LTGM after the fact.

**Comment by Oletus** [comment]
A while back it was decided that WebGL should allow some types of non-constants in global initializers, since this had been the behavior historically. If that causes issues on the drivers of a specific vendor, a workaround should be added to shader translators such as ANGLE so that non-constant global initializers get put in a function. I don't think the test should have been changed, can we revert this?

https://www.khronos.org/registry/webgl/specs/latest/1.0/#6.30

**Comment by zhenyao** [comment]
What about we add a specific test for global initializers with non-constants and remove that from other tests?  This way testing the behavior is isolated and if we ever encounter a driver that's spec compliant, running conformance tests and failing that specific test will make it clear what the issue is.

**Comment by kenrussell** [comment]
Mo, that's a good idea. Olli, this test was added specifically to test ternary operators in initializers, and the spec's clear that the two arms of the ternary operator must be constant expressions, so this strongly seemed like a bug in the test. Let's add other tests verifying the behavior of other non-constants in global initializers.

**Comment by Oletus** [comment]
Actually, now that I think of it I don't think that the test works as intended after this commit - now the ternary operator will just end up being constant folded, when the problem that this patch exposed was that the non-constant ternary operator was being converted to if statements in ANGLE, which wasn't appropriate in the global scope.

There's also already a specific test for global initializers with non-constants, but only in the 1.0.4 suite, not in the 1.0.3 suite.

**Comment by kenrussell** [comment]
That might be true with ANGLE as the shader translator but isn't necessarily how Microsoft's WebGL implementation works; the test was originally contributed by Microsoft and this change was LGTM'd by them above.

Let's add more tests verifying the behavior of global initializers with non-constants as you see necessary. This one previously violated the spec, and I think the complaint that was raised by one vendor was valid.

**Comment by Oletus** [comment]
I wasn't aware that Microsoft contributed the test, but it did reveal a bug in ANGLE, and now that coverage is thrown away. I can't say I agree with that.

Essentially, to restore coverage, I'd just want to add this same test back to the test suite. But would that be accepted, if the complaint about the test is seen as valid? I can see some reason for removing the test from the 1.0.3 suite, as it wasn't correct according to the WebGL spec at the time when 1.0.3 was frozen, but I don't understand why we shouldn't have it in the TOT conformance suite, unless we want to revisit the spec as well.

**Comment by kenrussell** [comment]
Apologies, I didn't realize this test was essentially a regression test for an ANGLE bug.

Could you please add another case to sdk/tests/conformance/glsl/misc/global-variable-init.html (or some other place) in the top of tree conformance suite testing the specific condition you're interested in? Let's please also make sure that the associated section in the WebGL specification https://www.khronos.org/registry/webgl/specs/latest/1.0/#6.30 ensures that this is required to work.

**Pull request merged**
