### PR TITLE
Fix test using sequence operator on arrays

### PR DESCRIPTION
**Pull request by Kangz**

### CODE REVIEW

**Comment by zhenyao** [comment]
@Oletus I thought this is legal?

**Comment by Kangz** [comment]
It isn't in WebGL, see https://www.khronos.org/registry/webgl/specs/latest/2.0/#5.26

**Comment by zhenyao** [comment]
Then instead of removing the test case, we should test the compile / link fails.

**Comment by Kangz** [comment]
It is tested in https://github.com/KhronosGroup/WebGL/blob/master/sdk/tests/conformance2/glsl3/forbidden-operators.html#L78 and the translator fix for forbidden-operators had a failure in complex-indexing, leading to this PR.

**Comment by zhenyao** [comment]
OK, thanks.

**Pull request merged**
