### PR TITLE
Generate INVALID_ENUM if internal format is not acceptable for TexImage3D

### PR DESCRIPTION
**Pull request by qkmiao**

### CODE REVIEW

**Comment by qkmiao** [comment]
Seems there are errors in the man pages: 
https://www.khronos.org/opengles/sdk/docs/man/xhtml/glTexImage2D.xml
https://www.khronos.org/opengles/sdk/docs/man3/html/glTexImage3D.xhtml

**Comment by zhenyao** [comment]
Note that the internalformat is actually GLint type, not GLenum type. That indicates an INVALID_VALUE error, not an INVALID_ENUM error.

**Comment by kenrussell** [comment]
Agree with Mo's assessment. Both TexImage2D and TexImage3D generate INVALID_VALUE in this case. The WebGL implementations need to be updated, not the tests.

I do see that the native test allows either GL_INVALID_VALUE or GL_INVALID_OPERATION for this case, so updating the test to allow either would be acceptable.

Closing this pull request in the meantime.

**Comment by qkmiao** [comment]
Thanks @zhenyao @kenrussell . It's a little strange internalformat is GLint type for TexImage* while GLenum for other APIs (compressedTexImage*, copyTexImage*). Also my Linux desktop Nvidia driver report INVALID_ENUM for texImage*. 

However, I will follow ES spec to clean texImage* in command buffer and blink.

**Comment by zhenyao** [comment]
It does seem strange to me. I hope there is a good reason for that.

**Comment by qkmiao** [comment]
I found in WebGL 1.0 and 2.0 spec GLenum internalformat was accepted by TexImage2D, but TexImage3D accepted GLint internalformat. Should WebGL spec align with GLES spec? WDYT @zhenyao @kenrussell ?

**Comment by zhenyao** [comment]
I think it's a mistake in WebGL spec.  It should be aligned with the ES2/ES3 spec.

**Comment by kenrussell** [comment]
Yes. I vaguely recall early in WebGL 1.0 spec development that the type of this argument was changed, but agree that the WebGL spec should align with the ES spec.

**Pull request closed without merging**
