### PR TITLE
Use more concise assertions in buffer-offscreen-test.html

### PR DESCRIPTION
**Pull request by MichalKrasowski**
There are more concise assert functions available. Let's use them.

### CODE REVIEW

**Comment by kainino0x** [comment]
lgtm, thanks for the contribution!

**Comment by MichalKrasowski** [comment]
@kainino0x , there seems to be a problem with my Contributor License Agreement.
I have accepted the license, but it doesn't seem to work.

**Comment by michal-krasowski-red** [comment]
Accidentally published from my company's account. Accepted the license using the other account as well.

**Comment by MichalKrasowski** [comment]
You can merge now :smile:

**Comment by jdashg** [comment]
Thanks!

**Pull request merged**
