### PR TITLE
Simplify test case of texparameter-test.html

### PR DESCRIPTION
**Pull request by legendlee1314**
1. Remove world transformation.
2. Use WebGLTestUtils to setup texture quad.

### CODE REVIEW

**Comment by legendlee1314** [comment]
PTAL. Thanks!

**Comment by kenrussell** [comment]
This pull request does more than just this -- it also removes the array of textures set up at the beginning. While creating those textures one at a time may be functionally equivalent, I'm concerned that we may be losing key aspects of this longstanding test.

We'll need to carefully review these changes together.

**Comment by zhenyao** [comment]
Can you address kbr's concern and put back the texture array, and modify runDrawingTest(param) to also take a texture parameter.

**Comment by legendlee1314** [comment]
Put the texture array back. Please review.

**Comment by zhenyao** [comment]
LGTM
@kenrussell Ken, do you have more concerns?

**Comment by kenrussell** [comment]
The revised test looks OK. My main concern is around changing the logic of these tests too much, and accidentally losing test coverage; but after looking through the verification code, it seems it's pretty similar. Thanks for this simplification.

**Pull request merged**
