### PR TITLE
Split transform feedback tests into semantically useful groups.

### PR DESCRIPTION
**Pull request by kenrussell**

### CODE REVIEW

**Comment by kenrussell** [comment]
@zhenyao please review. Tested locally and manually. Verified the right tests showed up in the right HTML files.

**Comment by zhenyao** [comment]
You will also want to delete the original transformfeedback.html

**Comment by kenrussell** [comment]
Thanks for the feedback. transformfeedback.html is deleted by this patch. It showed up as a rename of the original .html file into one of the autogenerated ones, plus edits.

**Comment by zhenyao** [comment]
OK, thanks for pointing this out - I didn't realize.

**Pull request merged**
