### PR TITLE
quite a small fix

### PR DESCRIPTION
**Pull request by Richard-Yunchao**
PTAL.

### CODE REVIEW

**Comment by kenrussell** [comment]
Please use a descriptive comment in all commit messages, no matter how small. Perhaps something like "Removed incorrect deleteRenderbuffer call". Could you please amend the commit?

**Comment by Richard-Yunchao** [comment]
Done.

**Comment by Richard-Yunchao** [comment]
One more small change is merged into this pull request. PTAL. Thanks!

**Comment by toji** [comment]
Thanks for the better commit message. LGTM.

**Comment by kenrussell** [comment]
LGTM after the fact.

**Pull request merged**
