### PR TITLE
Add Blend Integer Min/Max Test

### PR DESCRIPTION
**Pull request by lexaknyazev**
This test was ported from the ANGLE's end2end `BlendIntegerTest` suite.

Known failures:
- [macOS/OpenGL/Intel](https://crbug.com/angleproject/5125) (invalid result after the draw call);
- ~~[Windows/Vulkan/Intel](https://crbug.com/angleproject/5071) (same as above, already fixed in drivers about a year ago)~~;
- [Android/Vulkan/Adreno](https://crbug.com/angleproject/5126) (driver crash).

### CODE REVIEW

**Review by kenrussell — APPROVED** [review]
Thanks for the targeted test.

The code looks good to me and it's currently passing on Chrome, Firefox and Safari on macOS (including on the Intel GPU, it looks like), so merging now.

**Comment by lexaknyazev** [comment]
> Firefox and Safari on macOS

That's interesting. Just in case, could you please run the `BlendIntegerTest.MRT*` end2end ANGLE tests on macOS with Intel GPU?

**Comment by greggman** [comment]
Is this what you want?
```
Note: Google Test filter = BlendIntegerTest.MRT*/ES3_OpenGL
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from BlendIntegerTest
[ RUN      ] BlendIntegerTest.MRTSigned/ES3_OpenGL
[       OK ] BlendIntegerTest.MRTSigned/ES3_OpenGL (114 ms)
[ RUN      ] BlendIntegerTest.MRTUnsigned/ES3_OpenGL
[       OK ] BlendIntegerTest.MRTUnsigned/ES3_OpenGL (28 ms)
[----------] 2 tests from BlendIntegerTest (143 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (144 ms total)
[  PASSED  ] 2 tests.
```

```
Note: Google Test filter = BlendIntegerTest.MRT*/ES3_Metal
[==========] Running 2 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 2 tests from BlendIntegerTest
[ RUN      ] BlendIntegerTest.MRTSigned/ES3_Metal
2021-12-02 16:13:48.575 angle_end2end_tests[62358:4581125] Using Metal Device: Intel(R) UHD Graphics 630
Shader compiler output: Metal
[       OK ] BlendIntegerTest.MRTSigned/ES3_Metal (226 ms)
[ RUN      ] BlendIntegerTest.MRTUnsigned/ES3_Metal
2021-12-02 16:13:48.751 angle_end2end_tests[62358:4581125] Using Metal Device: Intel(R) UHD Graphics 630
Shader compiler output: Metal
[       OK ] BlendIntegerTest.MRTUnsigned/ES3_Metal (120 ms)
[----------] 2 tests from BlendIntegerTest (346 ms total)

[----------] Global test environment tear-down
[==========] 2 tests from 1 test suite ran. (347 ms total)
[  PASSED  ] 2 tests.
```

**Comment by lexaknyazev** [comment]
@greggman 
Yes. These tests include the following line:
```
ANGLE_SKIP_TEST_IF(IsOpenGL() && IsOSX() && IsIntel());
```

Was it removed before running?

**Comment by lexaknyazev** [comment]
Btw, ANGLE CQ was using Intel Iris Graphics 5100 back then. Maybe the driver bug was limited to that GPU.

**Comment by greggman** [comment]
I get the same results with the checks removed but I'm not on old Intel.

**Comment by kenrussell** [comment]
@greggman thanks for finding and running these tests.

@lexaknyazev would you try putting up an ANGLE CL removing the skips? Our testing's moved off the old Intel Iris Graphics 5100 GPUs entirely at this point. Thanks in advance.

**Comment by greggman** [comment]
this CL has the checks removed. I just used it for testing. 

https://chromium-review.googlesource.com/c/angle/angle/+/3313778

**Comment by lexaknyazev** [comment]
Confirmed on macOS 10.15.7 that older Intel GPUs (likely all pre-Skylake) still have this bug when using OpenGL. Metal is not affected.

**Pull request merged**
