### PR TITLE
More similar fixes for texturespecification/ tests.

### PR DESCRIPTION
**Pull request by zhenyao**

### CODE REVIEW

**Comment by zhenyao** [comment]
@kenrussell Similar fixes to get deqp/functional/gles3/texturespecification/texsubimage2d_unpack_params.html pass

Please review

**Comment by zhenyao** [comment]
This CL also makes deqp/functional/gles3/texturespecification/texsubimage2d_pbo.html

**Comment by zhenyao** [comment]
This CL also makes the following two tests passing:

 deqp/functional/gles3/texturespecification/teximage3d_unpack_params.html
 deqp/functional/gles3/texturespecification/texsubimage3d_unpack_params.html

**Comment by zhenyao** [comment]
This CL also makes the following two tests passing:

deqp/functional/gles3/texturespecification/teximage3d_depth.html
deqp/functional/gles3/texturespecification/texsubimage3d_depth.html

**Comment by kenrussell** [comment]
Awesome work tracking these errors down and fixing them. LGTM.

**Pull request merged**
