### PR TITLE
Disallow FLOAT_32_UNSIGNED_INT_24_8_REV in TexSubImage{2|3}D

### PR DESCRIPTION
**Pull request by zhenyao**
@kenrussell @jdashg Please review.

### CODE REVIEW

**Comment by zhenyao** [comment]
Note that the texImage{2|3}D part is already there.  texSubImage{2|3}D part is simply an negligence to be fixed.

**Comment by kenrussell** [comment]
Looks good to me. Let's let @jdashg review too.

**Comment by jdashg** [comment]
I'm not sure I agree with the rationale, but I can accept that this normalizes the spec's treatment of the matter.
I think we should look into relaxing this later.

Actually, isn't this a result of D3D-ANGLE's limitations as seen in ANGLE_depth_texture. IIRC, we couldn't upload depth data in D3D, hence ANGLE_depth_texture's limitations.
If this is still the case, this should be the rationale for forbidding depth (and stencil?) uploads.

Please check with ANGLE before merging the wrong rationale.

**Comment by zhenyao** [comment]
I think the limitation you mentioned is D3D9 only and not in D3D11, but @null77 can you confirm?

**Comment by zhenyao** [comment]
OK, I'll remove the rationale and land this first.

**Comment by zhenyao** [comment]
The rationale removed. Merging this.

**Comment by null77** [comment]
It's certainly quite easy to upload depth and stencil data in D3D11. I believe this is not possible in D3D9, so as you said Mo, it makes sense that the restriction was created for D3D9.

**Pull request merged**
