### PR TITLE
Yield an INVALID_OPERATION error when trying to bind a deleted object

### PR DESCRIPTION
**Pull request by emilio**
cc #1991

### CODE REVIEW

**Comment by zhenyao** [comment]
Looks fine to me.  Thanks for the effort.  We will make conformant implementation non-conformant due to the back port, but this is trivia corner case and a fix should be easy, so probably OK.

@kenrussell @RafaelCintron @grorg @kenrussell @jdashg any objections we merge this?

**Comment by kenrussell** [comment]
Thanks @emilio for looking into this and making these changes.

May I please ask you to also do the following:

1) Update the top-of-tree version of the conformance test under sdk/tests/conformance/misc/object-deletion-behaviour.html

2) Update the spec under specs/latest/1.0/index.html defining this behavior for all of the bind* operations

Please squash commits when doing this (you will probably have to use the --force argument to git push to re-upload per https://www.khronos.org/webgl/wiki/Using_Github_To_Contribute )

Thanks very much.

**Comment by emilio** [comment]
No problem! :)

I think that should be pretty much it, I'm double-checking that Firefox doesn't have any expected failure that could affect this.

**Comment by kenrussell** [comment]
Thank you @emilio . Looks great. I hate to ask -- would it be much trouble for you to update specs/latest/2.0/index.html too?

**Comment by emilio** [comment]
Sure, just did it, and the tests should be ok, just checked  and there isn't any test that exercises this disabled in Gecko.

**Comment by kenrussell** [comment]
Excellent. Thank you very much for this thorough fix!

**Comment by kenrussell** [comment]
I realized too late that the earlier conformance snapshots need to admit both behaviors. Only the top of tree one should enforce the new behavior. If it's possible for you to revise the snapshots I'd appreciate it...

**Comment by emilio** [comment]
Sure, I'll do, no problem :-)

**Pull request merged**
