### PR TITLE
Revert part of https://github.com/KhronosGroup/WebGL/pull/1643

### PR DESCRIPTION
**Pull request by zhenyao**
This part caused a regression in deqp/functional/gles3/fbostencilbuffer.html

### CODE REVIEW

**Comment by zhenyao** [comment]
@xhcao FYI. Please take a look when you have time.

**Comment by zhenyao** [comment]
Merging myself.

**Comment by zhenyao** [comment]
@qkmiao also FYI

**Comment by xhcao** [comment]
@zhenyao , I will take a look it, thank you.

**Pull request merged**
