### PR TITLE
Remove a few test cases from fbodepthbuffer due to NVidia Linux drive…

### PR DESCRIPTION
**Pull request by zhenyao**
…r bugs.

### CODE REVIEW

**Comment by zhenyao** [comment]
@kenrussell @Kangz @jdashg FYI

**Comment by Kangz** [comment]
LGTM after the fact, thanks for handling this!

**Comment by jdashg** [comment]
Isn't finding these bugs what we have tests for?
Please revert.

@zhenyao @grorg @kenrussell @RafaelCintron

**Comment by zhenyao** [comment]
We agreed not to block WebGL 2 release by non-critical driver bugs.  These tests are not removed permanently.  We should add a mechanism to track them and add them back as the driver bugs being fixed by drivers.

We can do 1) create issues to track them; 2) add a mechanism to let them still be run for future WebGL 2 versions, just like the --min-version flag.

**Comment by zhenyao** [comment]
For what it's worth, tcuSkipList is a central place for all the skipped tests in deqp, so it's not like we will lose them in the stack of numerous test cases.

**Comment by jdashg** [comment]
You cannot disable your way to victory over conformance. I stand against skipping tests, particularly ones as well-founded as this one.

Having failures in the conformance suite does not strictly-speaking block release. If it blocks yours, I recommend you reconsider that, rather than disable well-founded tests.

Let's discuss this on the WG call this Thursday.

**Comment by zhenyao** [comment]
Let's discuss this on Thursday.  Just for your information, every entry we put into this skip list, we spent time studying and verifying it's indeed a driver bug, and isolating to the root cause of the wrong behavior. Then we file bugs against driver vendors. This is for the benefit of WebGL 2 in general.

**Pull request merged**
