### PR TITLE
Add test: getExtension while PBO is bound should not crash

### PR DESCRIPTION
**Pull request by kainino0x**
Regression test for [Chromium Issue 641643](https://bugs.chromium.org/p/chromium/issues/detail?id=641643)

### CODE REVIEW

**Comment by kenrussell** [comment]
Looks good, but could you please add the new test to conformance2/misc/00_test_list.txt as well? Please squash commits when doing so, and use the --force argument to git push if necessary to re-upload. Thanks.

**Comment by kainino0x** [comment]
Okay, done.

**Comment by kenrussell** [comment]
Thanks, looks great. Merging.

**Comment by zhenyao** [comment]
Good job!

**Pull request merged**
