### PR TITLE
Fix A8-on-R8 swizzle test on Chrome

### PR DESCRIPTION
**Pull request by lexaknyazev**
Fixes this test on Chrome due to #2818.

### CODE REVIEW

**Comment by lexaknyazev** [comment]
I think that this particular test (active vs bound texture) shouldn't depend on an unrelated implementation issue that could be resolved separately.

**Comment by lexaknyazev** [comment]
> `gl_PointSize` should always be being clamped to within the point size range, which does not allow zero.

GLES doesn't suggest that (from 3.0 section 3.4):
> If the value written to `gl_PointSize` is less than or equal to zero, or if no value is written, the point size is undefined.

**Comment by jdashg** [comment]
To ensure safe behavior, browsers must ensure that gl_PointSize is clamped to within its valid values, even if otherwise undefined.


The ES3 spec says two things here:
```

**Comment by jdashg** [comment]
I filed #2822 to add an explicit test for this.
Curiously, with transform-feedback enabled, chrome passes this test.
This sounds a lot like Chrome is being over-eager to skip draw calls.

**Comment by jdashg** [comment]
Let's talk about this in that PR, but I generally don't like working around implementation bugs in unrelated tests.

**Comment by jdashg** [comment]
To keep coverage, I would like to resolve #2822 before merging this.

**Comment by kenrussell** [comment]
This test was not intended to test the undefined behavior of failing to write gl_PointSize in a vertex shader used to draw points. Let's continue to discuss that in #2818 and #2822 . Merging this now.

**Pull request merged**
