### PR TITLE
fix read-pixels-from-fbo-test.

### PR DESCRIPTION
**Pull request by mephisto41**
There are 2 problems in this test.
1. The readback value of SRGB8_ALPHA8 didn't consider sRGB conversion.
2. If type is integer or float, calling getParameter with IMPLEMENTATION_COLOR_READ_FORMAT/TYPE would cause gl error then test will fail.

### CODE REVIEW

**Comment by zhenyao** [comment]
I don't find any spec text supporting 2.  If it's not in the spec, then it's a driver bug and we definitely should test it.

**Comment by kenrussell** [comment]
Agree with Mo -- I don't see anything in the spec that would support change (2). It sounds to me like Firefox's WebGL 2.0 implementation is what's generating the error, not the OpenGL implementation. (This test currently passes on Chrome's WebGL 2.0 prototype.)

**Comment by mephisto41** [comment]
Ah, I am confused with this spec. https://www.opengl.org/registry/specs/ARB/ES2_compatibility.txt

I'll check our implementation. Thanks.

**Comment by kenrussell** [comment]
@mephisto41 please do open a new pull request for change (1) if you've double-checked and there is a bug in the test. Chrome currently passes the test but there could certainly still be a bug.

**Pull request closed without merging**
