### PR TITLE
Add a test to verify that transformfeedback unwritten output

### PR DESCRIPTION
**Pull request by zhenyao**
defaults to zero.

Note that this test fails in Linux NVidia with random output values.

This is WebGL2 specific behavior.
See https://github.com/KhronosGroup/WebGL/pull/1861

### CODE REVIEW

**Comment by zhenyao** [comment]
@kenrussell Please review.

**Comment by kenrussell** [comment]
Excellent. LGTM. Please merge yourself once the other pull request is merged.

**Comment by Richard-Yunchao** [comment]
@zhenyao , should we do sth in Chromium (and in other browsers) to get the correct result? By default, the value for any output variable specified to be streamed to a buffer object but not actually written by a vertex shader is undefined.

**Comment by zhenyao** [comment]
That needs to be handled in ANGLE's shader translator, where we initialize all output variables to 0.

**Pull request merged**
