### PR TITLE
Fix lint errors in conformance-suites/1.0.3

### PR DESCRIPTION
**Pull request by renchenglei**
In order to improve the code quality and consistency, web-platform-test use a [lint tool](https://github.com/w3c/web-platform-tests#lint-tool) for catching common mistakes in test files.

### CODE REVIEW

**Comment by renchenglei** [comment]
@Richard-Yunchao @zqzhang @Honry ptal, thanks~

**Comment by Honry** [comment]
LGTM

**Comment by Richard-Yunchao** [comment]
LGTM. Thanks for the efforts to clean the code.

**Comment by zhenyao** [comment]
LGTM
Can you also help cleaning up the top of tree test suite?

**Comment by renchenglei** [comment]
@zhenyao  OK. No problem.

**Comment by zhenyao** [comment]
Did you already clean up the lint errors in sdk/test? Since there are so many files, I can't really review and see which files are processed or which are not.

For older versions, it's not that important because we hardly ever touch them anymore, but if it's convenient on your side to do the cleanup, then it would be nice.

**Comment by kenrussell** [comment]
@renchenglei , @zhenyao is talking about the top-of-tree test suite, which is under sdk/tests/ . conformance-suites/ contains fixed snapshots. It's not necessary or desired to touch 1.0.0 / 1.0.1 / 1.0.2.

**Comment by renchenglei** [comment]
@kenrussell @zhenyao the pr just cleaned the lint errors in conformance/1.0.3. I will clean up the top-of-tree test suite.

**Pull request merged**
