### PR TITLE
Generate INVALID_VALUE for TexImage with invalid internalformat

### PR DESCRIPTION
**Pull request by qkmiao**
Align with spec change in https://github.com/KhronosGroup/WebGL/pull/1402.

### CODE REVIEW

**Comment by zhenyao** [comment]
lgtm

**Comment by zhenyao** [comment]
Forgot to mention: can you also merge this back to older version of conformance tests?  In older version, we will want to accept both INVALID_VALUE and INVALID_ENUM, so we don't regress already certified conformant implementations.

**Comment by qkmiao** [comment]
@zhenyao it seems no TexImage3D tests in older conformance tests. I sent a pull request to fix TexImage2D at: https://github.com/KhronosGroup/WebGL/pull/1414.

**Comment by zhenyao** [comment]
Thanks.

**Pull request merged**
