### PR TITLE
Remove maxShaderCompilerThreadsKHR (#2772)

### PR DESCRIPTION
**Pull request by jchen10**

### CODE REVIEW

**Comment by jchen10** [comment]
@kenrussell PTAL

**Comment by jdashg** [comment]
This is what I remember our decision being. Thanks for making the change!

**Comment by kenrussell** [comment]
Yes, this is what was agreed on. Thanks @jchen10 for taking care of this!

**Comment by jchen10** [comment]
Thank you all reviewing!

**Pull request merged**
