### PR TITLE
Initialize variable expandoValue before using it

### PR DESCRIPTION
**Pull request by qkmiao**
@toji please help to review, thanks!

### CODE REVIEW

**Comment by RafaelCintron** [comment]
@qkmiao , I am confused. ExpandoValue is only used in setTestExpandos and verifyTestExpandos and it is initialized before those two functions. It does not need to be initialized earlier and, in my opinion, the code reads better if it is initialized close to where it is used.

**Comment by kenrussell** [comment]
Agreed -- this pull request does not make sense.

**Comment by qkmiao** [comment]
@RafaelCintron @kenrussell , thanks for review. ExpandoValue is used when calling testBasicBindings() (which will call setTestExpandos and verifyTestExpandos ). So I think it should be initialized before testBasicBindings.

**Comment by RafaelCintron** [comment]
Apologies @qkmiao , I now see your point.  Since testBasicBindings runs before expandoValue is set to "Webgl is awesome!", the expandos set on the object end up with the value of undefined, instead of the string. I think we should merge this pull request.

**Comment by kenrussell** [comment]
@qkmiao , sorry for being hasty. Thanks for your proposed fix.

The control flow in this file is confusing. Could you please fix this instead by pulling the "// Run tests" section down to the bottom, just above "var successfullyParsed = true;"? Please update your pull request and comment here when done. Thanks.

**Comment by qkmiao** [comment]
@kenrussell , the pull request has been updated. Please take another look.

**Comment by kenrussell** [comment]
@qkmiao , thank you for this fix and sorry for misunderstanding it the first time. Looks good.

**Pull request merged**
