### PR TITLE
Fix integer precision issue for cube map texture sampling on Android

### PR DESCRIPTION
**Pull request by qkmiao**
Highp integers have exactly 32 bits of precision, while mediump and lowp
integers have implementation-defined numbers of bits, see section 4.1.3
Integers in ESSL 3.00 spec. Default precision of integer in fragment
shader is mediump, see section 4.5.4 Default Precision Qualifiers in
ESSL 3.00 spec. So the condition expression in cube map texture sampling
shaders will be undefined. This caused cube map related texture
conformance tests to fail on Andorid where mediump may be implemented in
16 bits.

### CODE REVIEW

**Comment by qkmiao** [comment]
With this pr, all conformance2/textures/* passed on Nexus 6.  This fixed chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=569836.

**Comment by kenrussell** [comment]
*Thank you* Qiankun for tracking down this test bug.

Would you please merge it back to the conformance-suites/2.0.0 snapshot, too? This has been a longstanding bug preventing conformance on Android.

Thank you again!

**Comment by qkmiao** [comment]
Backported to 2.0.0 snapshot.

**Comment by zhenyao** [comment]
Thank you for getting the bottom of this!

LGTM

**Pull request merged**
