### PR TITLE
Propose WEBGL_sync and WEBGL_es3_buffers.

### PR DESCRIPTION
**Pull request by jdashg**
Together these allow for efficient async readback, as well as supporting PBO-based GPU feedback iteration.

### CODE REVIEW

**Comment by kenrussell** [comment]
This is a lot of functionality to pull into WebGL 1.0. @kainino0x @jdarpinian and I discussed this more today and we remain concerned that trying to optimize the synchronous API to do efficient readbacks is going to lead to performance pitfalls and a lot of implementation complexity.

We would rather pursue the more explicit asynchronous readback API that @kainino0x has been working on, because it is a step toward a primitive that we would collectively want in the GPUWeb API. I think we can all agree that we would not want to design GPUWeb's readbacks to emulate OpenGL's style, but instead be explicitly asynchronous.

@grorg @RafaelCintron do you have any comments on this pull request?

**Comment by jdashg** [comment]
I don't think the async API is what we necessarily want in GPUWeb, and I don't think this is a good place to prototype that.

**Comment by kenrussell** [comment]
Per discussion in the working group: we are going to postpone making these proposals, and for the moment, try to focus our engineering efforts on making it possible for Edge and Safari to ship WebGL 2.0.

**Comment by jdashg** [comment]
Closing in favor of recommending WebGL 2.

**Pull request closed without merging**
