### PR TITLE
Add a test to cover an unreferenced varyings bug in ANGLE.

### PR DESCRIPTION
**Pull request by null77**
See http://crbug.com/651493

PTAL @kenrussell @zhenyao

### CODE REVIEW

**Comment by zhenyao** [comment]
I am curious: what's so specific about unreferenced variables to be of number 2? If we have only one unreferenced variable, without the ANGLE fix, it runs OK?

**Comment by null77** [comment]
Yes, there's an early-exit of a for loop. Works fine for one variable, 2+ fails.

**Comment by zhenyao** [comment]
LGTM

**Comment by kenrussell** [comment]
Excellent! Thank you Jamie for the conformance test.

**Pull request merged**
