### PR TITLE
move all files under sdk/tests/conformance/resources/ to sdk/tests/resources/

### PR DESCRIPTION
**Pull request by Richard-Yunchao**
Please take a look when you have time. This is discussed in #937

### CODE REVIEW

**Comment by kenrussell** [comment]
Thank you for doing this renaming. I tested it locally and it looks good. I think it's a good direction so the resources can be shared between the WebGL 1.0 and 2.0 suites. Merging now.

**Comment by Oletus** [comment]
This seems to have broken sdk/tests/resources/tex-image-and-sub-image-2d-with-image.js and sdk/tests/resources/tex-image-and-sub-image-2d-with-video.js. They're trying to load red-green.* files from an absolute path instead of a relative path.

**Comment by Oletus** [comment]
Same issue also in sdk/tests/resources/gl-object-get-calls.js

**Comment by zhenyao** [comment]
Now we are refactoring more tests into js, it seems ill-organized if we put all the js tests into resources and the originally well-organized sub folders only contain the containing html files.

What about putting such js files at the same folder with their container html files?

**Comment by zhenyao** [comment]
Per discussion with kbr, we are moving js files out of resources/ and into js/, and under js/ we create utils/ and tests/

**Comment by zhenyao** [comment]
I am going to prepare a pull request for this, which will also fix the issues Olli pointed out.

**Comment by Richard-Yunchao** [comment]
@zhenyao , totally agree with you. This is a good idea. I also want to put all js files into a standalone file folder. Per the issue @Oletus pointed out, IIRC, the previous code also used an absolute path, so I think it was OK. You know, I use "python -m SimpleHTTPRequest" under sdk/tests in my local machine, so no test failed with this patch. If it does cause errors, please help to fix them. Thanks a lot!

**Pull request merged**
