### PR TITLE
add WebGL 1 test for uninitialized buffers

### PR DESCRIPTION
**Pull request by kainino0x**

### CODE REVIEW

**Comment by kainino0x** [comment]
@zhenyao PTAL

**Comment by zhenyao** [comment]
The test looks great!  Can you get a follow up patch to test bufferData(null) and bufferSubData() only fills a subset, and verifies the range bufferSubData doesn't touch is initialized to zero.

**Comment by zhenyao** [comment]
Ah, just realized you forgot to update the 00_test_list.txt file

**Comment by kainino0x** [comment]
> follow up patch

Sure, I'll do that.

> 00_test_list.txt

Ugh, I keep forgetting to do that. Thanks for fixing it.

**Pull request merged**
