### PR TITLE
[WEBGL_multi_draw] Align with Web IDL specification

### PR DESCRIPTION
**Pull request by autokagami**
🤖 This is an automated pull request to align the spec with the latest Web IDL specification. 🤖

The followings are the Web IDL validation messages, which may help understanding this PR:

* ```
  Validation error at line 3 in WEBGL_multi_draw,0, inside `interface WEBGL_multi_draw -> extended-attribute NoInterfaceObject`:
  [NoInterfaceObject]
   ^
  ```
  
  > Error: `[NoInterfaceObject]` extended attribute is a legacy feature that is now renamed to `[LegacyNoInterfaceObject]`. Refer to the [relevant upstream PR](https://github.com/heycam/webidl/pull/870) for more information.
* ```
  Validation error at line 4 in WEBGL_multi_draw,0, inside `interface WEBGL_multi_draw`:
  interface WEBGL_multi_draw {
            ^
  ```
  
  > Error: Interfaces must have `[Exposed]` extended attribute. To fix, add, for example, `[Exposed=Window]`. Please also consider carefully if your interface should also be exposed in a Worker scope. Refer to the [WebIDL spec section on Exposed](https://heycam.github.io/webidl/#Exposed) for more information.

Currently this autofix might introduce awkward code formatting, and feel free to manually fix it whenever it happens.

Please file an issue at https://github.com/saschanaz/webidl-updater/issues/new if you think this is invalid or should be enhanced.

### CODE REVIEW

**Comment by kenrussell** [comment]
Looks like this one might still need to be handled @jdashg .

**Comment by foolip** [comment]
@kenrussell @jdashg this is one of many open PRs like this, https://github.com/KhronosGroup/WebGL/pulls?q=is%3Apr+is%3Aopen+nointerfaceobject is the full list.

Is there something that needs to be done to make it possible to merge all of these?

cc @saschanaz

**Comment by jdashg** [comment]
This will be handled by #3279.
We can't accept Contributions without a signed CLA, as the CLA bot has stated in each of these PRs.
It's easy enough to do these changes ourselves, but we can't take Contributions from CLA. Someone has to be responsible for it.

**Comment by saschanaz** [comment]
WHATWG special cased this bot; could we do the same here? I can sign it with my name, though.

**Comment by jdashg** [comment]
@outofcontrol ^

**Comment by outofcontrol** [comment]
If we whitelist @autokagami  in the CLA, who does liability fall to in case of a dispute in the code?

**Comment by saschanaz** [comment]
Theoretically the bot cannot write any disputable code since changes from the bot never affects any behavior or API form. What's the policy for such changes?

**Comment by jdashg** [comment]
Basically the bot needs a human to take responsibility for it, which includes being responsible for any mistakes. (even though it's not supposed to do anything Bad!) 
If you can sign the CLA for the bot, @saschanaz, I think that's clearest here.

**Comment by saschanaz** [comment]
I can do that, but kinda hoped there is a way to mark a PR as non-substantive as w3c ash-nazg does 🤔

**Comment by outofcontrol** [comment]
This question has been run up the legal flag pole for review. Will post back here once we have an answer.

**Comment by kenrussell** [comment]
Handled in #3279 .

**Pull request closed without merging**
