### PR TITLE
Added test for checking sequence operators returns constant values for WebGL 1.0

### PR DESCRIPTION
**Pull request by matthewn4444**
…

### CODE REVIEW

**Comment by matthewn4444** [comment]
Addressing the RHS for the const var assignment, I think from the spec here: https://www.opengl.org/registry/doc/GLSLangSpec.Full.1.20.8.pdf

4.3.2 Const says: __Initializers for const declarations must be constant expressions, as defined in Section 4.3.3 “Constant Expressions.”__

4.3.3 Constant Expressions

A constant expression is one of
* a literal value (e.g., 5 or true)
* a global or local variable qualified as const (i.e. not including function parameters)
* __an expression formed by an operator on operands that are all constant expressions, including getting an element or length of a constant array, or a field of a constant structure, or components of a constant vector.__
* a constructor whose arguments are all constant expressions
* a built-in function call whose arguments are all constant expressions, with the exception of the texture
lookup functions, the noise functions, and ftransform. The built-in functions dFdx, dFdy, and
fwidth must return 0 when evaluated inside an initializer with an argument that is a constant
expression

I am new to the spec and did not read all of it so I am not sure if this is what you want. If it is, then I can add this to the code as a comment or in the commit message.

**Comment by jdashg** [comment]
Yep, you're correct. `const` is compile-time in GLSL and ESSL. Leaving a small comment wouldn't hurt.

Regardless, this should be --min-version 1.0.4 before we can merge it.

**Comment by Oletus** [comment]
jdashg: Did you notice that the pull request was updated?

matthewn4444: It's good to send a comment to a pull request once you update it, I don't think there is an automatic notification if you simply push a new commit.

**Comment by matthewn4444** [comment]
I added the version number to the comment

**Comment by matthewn4444** [comment]
Sorry about that, I updated the comment again. Let me know if it is still wrong.

**Comment by jdashg** [comment]
Thanks!

**Pull request merged**
